Repository yoonms0617/happy-camping, pull requests merged in 2023-02, with the labels that each got.

#26 장바구니 페이지 추가
  project/src/main/webapp/happy/cart/cart.jsp
Labels: 화면

#28 -로그인,회원가입 기능 추가 / 검색어 폼 추가
  project/src/main/java/com/sist/dao/MemberDAO.java
  project/src/main/java/com/sist/model/MemberModel.java
  project/src/main/java/com/sist/temp/MainClass.java
  project/src/main/java/com/sist/vo/MemberVO.java
  project/src/main/webapp/assets/images/main/search/search.png
  project/src/main/webapp/assets/project/member/js/login.js
  project/src/main/webapp/assets/project/member/js/signup.js
  project/src/main/webapp/happy/fragments/header.jsp
  project/src/main/webapp/happy/member/login.jsp
  project/src/main/webapp/happy/member/login_result.jsp
  project/src/main/webapp/happy/member/signup.jsp
Labels: 기능, 화면

#31 feat: 캠핑장 검색 기능 추가
  project/src/main/java/com/sist/dao/CampDAO.java
  project/src/main/java/com/sist/model/CampModel.java
  project/src/main/java/com/sist/util/Pagination.java
  project/src/main/webapp/happy/camp/camp_list.jsp
Labels: 기능, 화면

#34 회원가입시 전화번호 유효성 검증을 하지 않는 버그 해결
  project/src/main/webapp/assets/project/member/js/signup.js
  project/src/main/webapp/happy/member/signup.jsp
Labels: 버그, 화면

#35 feat: 공지사항 페이지 및 기능 추가
  project/src/main/java/com/sist/dao/NoticeDAO.java
  project/src/main/java/com/sist/model/NoticeModel.java
  project/src/main/java/com/sist/util/Pagination.java
  project/src/main/webapp/WEB-INF/application.xml
  project/src/main/webapp/happy/camp/camp_list.jsp
  project/src/main/webapp/happy/fragments/navigation.jsp
  project/src/main/webapp/happy/notice/notice_detail.jsp
  project/src/main/webapp/happy/notice/notice_list.jsp
  project/src/main/webapp/happy/notice/notice_update.jsp
  project/src/main/webapp/happy/notice/notice_write.jsp
Labels: 기능, 화면

#37 앞 또는 뒤로 이동할 수 없는데 페이징 앞, 뒤 이동 버튼이 보여지는 문제 해결
  project/src/main/java/com/sist/util/Pagination.java
  project/src/main/webapp/happy/camp/camp_list.jsp
  project/src/main/webapp/happy/notice/notice_detail.jsp
  project/src/main/webapp/happy/notice/notice_list.jsp
Labels: 버그, 화면

#38 메인페이지 로고, 글씨체 변경
  project/src/main/java/com/sist/dao/CampDAO.java
  project/src/main/java/com/sist/dao/CampReviewDAO.java
  project/src/main/java/com/sist/dao/ItemDAO.java
  project/src/main/java/com/sist/dao/MemberDAO.java
  project/src/main/java/com/sist/dao/NoticeDAO.java
  project/src/main/java/com/sist/model/CampModel.java
  project/src/main/java/com/sist/model/MemberModel.java
  project/src/main/java/com/sist/model/NoticeModel.java
  project/src/main/java/com/sist/temp/MainClass.java
  project/src/main/java/com/sist/vo/MemberVO.java
  project/src/main/webapp/happy/fragments/hclogo.png
  project/src/main/webapp/happy/fragments/hclogo2.png
  project/src/main/webapp/happy/fragments/head.jsp
  project/src/main/webapp/happy/fragments/header.jsp
Labels: 화면

#41 - 메인페이지 검색기능 추가
  project/src/main/java/com/sist/dao/ItemDAO.java
  project/src/main/java/com/sist/model/ItemModel.java
  project/src/main/webapp/assets/project/search/css/search.css
  project/src/main/webapp/assets/project/search/js/search.js
  project/src/main/webapp/happy/fragments/header.jsp
  project/src/main/webapp/happy/search/search.jsp
  project/src/main/webapp/happy/search/search_detail.jsp
Labels: 기능, 화면

#42 - 메인페이지 검색창 폼 변경
  project/src/main/java/com/sist/model/ItemModel.java
  project/src/main/webapp/happy/fragments/header.jsp
Labels: 화면

#44 캠핑장 리뷰 댓글 페이징 버튼 안나오는 문제 해결
  project/src/main/java/com/sist/controller/DispatcherServlet.java
  project/src/main/java/com/sist/dao/CampDAO.java
  project/src/main/java/com/sist/dao/CampReviewDAO.java
  project/src/main/java/com/sist/dao/NoticeDAO.java
  project/src/main/java/com/sist/util/Pagination.java
  project/src/main/webapp/assets/project/camp/js/camp_review.js
Labels: 버그, 기능, 화면

#46 - 메인페이지 검색창 기능 변경
  project/src/main/java/com/sist/dao/ItemDAO.java
  project/src/main/java/com/sist/model/ItemModel.java
  project/src/main/webapp/happy/fragments/header.jsp
  project/src/main/webapp/happy/search/search.jsp
Labels: 기능

#47 자유게시판
  project/src/main/java/com/sist/dao/BoardDAO.java
  project/src/main/java/com/sist/model/BoardModel.java
  project/src/main/java/com/sist/vo/BoardVO.java
  project/src/main/webapp/WEB-INF/application.xml
  project/src/main/webapp/happy/board/board_detail.jsp
  project/src/main/webapp/happy/board/board_list.jsp
  project/src/main/webapp/happy/board/board_update.jsp
  project/src/main/webapp/happy/board/board_write.jsp
  project/src/main/webapp/happy/fragments/navigation.jsp
Labels: 기능, 화면

#49 장바구니 기능 추가, 주문 페이지 추가
  project/src/main/java/com/sist/dao/CartDAO.java
  project/src/main/java/com/sist/model/CartModel.java
  project/src/main/java/com/sist/vo/CartVO.java
  project/src/main/webapp/WEB-INF/application.xml
  project/src/main/webapp/happy/cart/cart.jsp
  project/src/main/webapp/happy/cart/order.jsp
  project/src/main/webapp/happy/fragments/header.jsp
Labels: 기능, 화면

#50 마이 페이지 화면, 기능 추가
  project/src/main/java/com/sist/dao/MyPageDAO.java
  project/src/main/java/com/sist/model/MyPageModel.java
  project/src/main/webapp/assets/project/camp/js/camp_review.js
  project/src/main/webapp/assets/project/member/js/mypage-board.js
  project/src/main/webapp/assets/project/member/js/mypage-like.js
  project/src/main/webapp/assets/project/member/js/mypage-review.js
  project/src/main/webapp/assets/project/member/js/mypage.js
  project/src/main/webapp/happy/fragments/header.jsp
  project/src/main/webapp/happy/member/mypage/address.jsp
  project/src/main/webapp/happy/member/mypage/board.jsp
  project/src/main/webapp/happy/member/mypage/home.jsp
  project/src/main/webapp/happy/member/mypage/like.jsp
  project/src/main/webapp/happy/member/mypage/modify.jsp
  project/src/main/webapp/happy/member/mypage/review.jsp
Labels: 기능, 화면

#51 커밋 비교, 아이템디테일 리뷰,qna수정중
  project/src/main/java/com/sist/controller/DispatcherServlet.java
  project/src/main/java/com/sist/dao/BoardDAO.java
  project/src/main/java/com/sist/dao/CartDAO.java
  project/src/main/java/com/sist/dao/ItemDAO.java
  project/src/main/java/com/sist/dao/ItemQnaDAO.java
  project/src/main/java/com/sist/dao/MyPageDAO.java
  project/src/main/java/com/sist/model/CartModel.java
  project/src/main/java/com/sist/model/ItemModel.java
  project/src/main/java/com/sist/model/MyPageModel.java
  project/src/main/java/com/sist/vo/BoardVO.java
  project/src/main/java/com/sist/vo/CartVO.java
  project/src/main/java/com/sist/vo/ItemQAVO.java
  project/src/main/java/com/sist/vo/ItemReviewVO.java
  project/src/main/webapp/assets/project/item/js/item_qna.js
  project/src/main/webapp/happy/item/item_detail.jsp
  project/src/main/webapp/happy/item/item_detail_temp.jsp
  project/src/main/webapp/happy/item/item_detail_temp22.jsp
  project/src/main/webapp/happy/item/item_list.jsp
  project/src/main/webapp/happy/item/item_qna_detail.jsp
  project/src/main/webapp/happy/item/item_qna_insert.jsp
  project/src/main/webapp/happy/item/item_qna_list.jsp
  project/src/main/webapp/happy/item/item_review_insert.jsp
  project/src/main/webapp/happy/item/item_review_insert_ok.jsp
  project/src/main/webapp/happy/item/item_review_update.jsp
  project/src/main/webapp/happy/item/item_review_update_ok.jsp
  project/src/main/webapp/happy/item/temp.jsp
  project/src/main/webapp/happy/item/temp2.jsp
Labels: 기능, 질문

#52 좋아요 기능 추가
  project/src/main/java/com/sist/dao/CampLikeDAO.java
  project/src/main/java/com/sist/dao/ItemLikeDAO.java
  project/src/main/java/com/sist/model/CampLikeModel.java
  project/src/main/java/com/sist/model/ItemLikeModel.java
  project/src/main/java/com/sist/model/MyPageModel.java
  project/src/main/java/com/sist/vo/CampLikeVO.java
  project/src/main/java/com/sist/vo/ItemLikeVO.java
  project/src/main/java/com/sist/vo/ItemReviewVO.java
  project/src/main/webapp/WEB-INF/application.xml
  project/src/main/webapp/assets/project/camp/js/camp_like.js
  project/src/main/webapp/assets/project/item/js/item_like.js
  project/src/main/webapp/assets/project/member/js/mypage-like.js
  project/src/main/webapp/happy/item/item_detail.jsp
  project/src/main/webapp/happy/item/item_list.jsp
  project/src/main/webapp/happy/member/mypage/like.jsp
  project/src/main/webapp/happy/search/search.jsp
Labels: 기능, 화면

#53 -메인페이지 최근본 상품 보는 퀵메뉴 기능 추가
  project/src/main/java/com/sist/dao/ItemDAO.java
  project/src/main/java/com/sist/model/ItemModel.java
  project/src/main/java/com/sist/model/MainModel.java
  project/src/main/webapp/assets/project/main/js/main.js
  project/src/main/webapp/happy/main/main.jsp
Labels: 기능, 화면

#54 - 퀵메뉴 기능 수정, 검색어 기능 수정
  project/src/main/java/com/sist/model/MainModel.java
  project/src/main/webapp/happy/main/main.jsp
  project/src/main/webapp/happy/search/search.jsp
Labels: 기능, 화면

#55 장바구니 버튼 처리
  project/src/main/webapp/happy/item/item_detail.jsp
Labels: 화면

#57 - 아이디 저장 기능 추가
  project/src/main/java/com/sist/model/ItemModel.java
  project/src/main/webapp/assets/project/member/js/login.js
  project/src/main/webapp/happy/member/login.jsp
Labels: 기능, 화면

#58 마이 페이지에 주문내역 목록 추가
  project/src/main/java/com/sist/dao/OrderDAO.java
  project/src/main/java/com/sist/model/OrderModel.java
  project/src/main/java/com/sist/vo/OrderItemVO.java
  project/src/main/java/com/sist/vo/OrderVO.java
  project/src/main/webapp/WEB-INF/application.xml
  project/src/main/webapp/assets/project/member/js/mypage-order.js
  project/src/main/webapp/happy/admin/home.jsp
  project/src/main/webapp/happy/member/mypage/home.jsp
Labels: 기능, 화면

#60 - 메인 페이지 퀵메뉴 기능 수정, 상품 목록 (경로 변경) , 장바구니 페이지 수정
  project/src/main/webapp/assets/project/main/js/main.js
  project/src/main/webapp/happy/cart/cart.jsp
  project/src/main/webapp/happy/item/item_list.jsp
  project/src/main/webapp/happy/main/main.jsp
Labels: 기능, 화면

#61 댓글기능 및 멤버 DAO수정
  project/src/main/java/com/sist/dao/BoardDAO.java
  project/src/main/java/com/sist/dao/MemberDAO.java
  project/src/main/java/com/sist/model/BoardModel.java
  project/src/main/java/com/sist/vo/BoardReplyVO.java
  project/src/main/java/com/sist/vo/BoardVO.java
  project/src/main/webapp/happy/board/board_detail.jsp
  project/src/main/webapp/happy/board/image/re_icon.png
Labels: 기능, 화면

#62 - 메인 페이지 상품 경로 추가, 관련 기능 메소드 추가
  project/src/main/java/com/sist/dao/ItemDAO.java
  project/src/main/java/com/sist/model/ItemModel.java
  project/src/main/java/com/sist/model/MainModel.java
  project/src/main/webapp/happy/main/main.jsp
Labels: 기능, 화면

#65 장바구니에서 상품 주문 기능 추가
  project/src/main/java/com/sist/dao/MemberDAO.java
  project/src/main/java/com/sist/dao/OrderDAO.java
  project/src/main/java/com/sist/model/OrderModel.java
  project/src/main/java/com/sist/vo/OrderVO.java
  project/src/main/webapp/WEB-INF/application.xml
  project/src/main/webapp/assets/project/member/js/mypage-order.js
  project/src/main/webapp/happy/cart/cart.jsp
  project/src/main/webapp/happy/cart/order.jsp
  project/src/main/webapp/happy/cart/order_detail.jsp
  project/src/main/webapp/happy/item/item_detail.jsp
Labels: 기능, 화면

#66 - 검색후 상품 페이지 화면 변경
  project/src/main/webapp/happy/search/search.jsp
Labels: 화면

#67 아이템 후기, 리뷰 완성
  project/src/main/java/com/sist/dao/BoardDAO.java
  project/src/main/java/com/sist/dao/CampLikeDAO.java
  project/src/main/java/com/sist/dao/CartDAO.java
  project/src/main/java/com/sist/dao/ItemDAO.java
  project/src/main/java/com/sist/dao/ItemLikeDAO.java
  project/src/main/java/com/sist/dao/ItemQnaDAO.java
  project/src/main/java/com/sist/dao/ItemQnaReDAO.java
  project/src/main/java/com/sist/dao/OrderDAO.java
  project/src/main/java/com/sist/model/BoardModel.java
  project/src/main/java/com/sist/model/CampLikeModel.java
  project/src/main/java/com/sist/model/CartModel.java
  project/src/main/java/com/sist/model/ItemLikeModel.java
  project/src/main/java/com/sist/model/ItemModel.java
  project/src/main/java/com/sist/model/MainModel.java
  project/src/main/java/com/sist/model/OrderModel.java
  project/src/main/java/com/sist/vo/BoardVO.java
  project/src/main/java/com/sist/vo/ItemQAReplyVO.java
  project/src/main/webapp/assets/project/item/js/item_qna.js
  project/src/main/webapp/happy/item/item_detail.jsp
  project/src/main/webapp/happy/item/item_list.jsp
  project/src/main/webapp/happy/item/item_qna_detail.jsp
  project/src/main/webapp/happy/item/item_qna_insert.jsp
  project/src/main/webapp/happy/item/item_qna_list.jsp
  project/src/main/webapp/happy/item/item_qna_update.jsp
Labels: 기능, 화면
