Repository yoonms0617/happy-camping, pull requests merged in 2023-01, with the labels that each got.

#4 design: 메인 페이지 추가
  project/src/main/webapp/assets/boostrap/css/bootstrap.min.css
  project/src/main/webapp/assets/boostrap/css/bootstrap.min.css.map
  project/src/main/webapp/assets/boostrap/js/bootstrap.min.js
  project/src/main/webapp/assets/boostrap/js/bootstrap.min.js.map
  project/src/main/webapp/assets/favicon/favicon-16x16.png
  project/src/main/webapp/assets/images/main/main-01.jpg
  project/src/main/webapp/assets/images/main/main-02.jpg
  project/src/main/webapp/assets/images/main/main-03.jpg
  project/src/main/webapp/assets/images/main/main-04.jpg
  project/src/main/webapp/assets/jquery/jquery-3.6.3.min.js
  project/src/main/webapp/assets/project/main/css/category.css
  project/src/main/webapp/assets/project/main/js/slider.js
  project/src/main/webapp/assets/slick/css/slick-theme.css
  project/src/main/webapp/assets/slick/css/slick.css
  project/src/main/webapp/assets/slick/js/slick.min.js
  project/src/main/webapp/happy/fragments/common-script.jsp
  project/src/main/webapp/happy/fragments/footer.jsp
  project/src/main/webapp/happy/fragments/head.jsp
  project/src/main/webapp/happy/fragments/header.jsp
  project/src/main/webapp/happy/fragments/navigation.jsp
  project/src/main/webapp/index.jsp
Labels: 화면

#6 프로젝트 수정
  project/.gitignore
  project/.settings/.jsdtscope
  project/.settings/org.eclipse.core.resources.prefs
  project/.settings/org.eclipse.jdt.core.prefs
  project/.settings/org.eclipse.wst.common.component
  project/.settings/org.eclipse.wst.common.project.facet.core.xml
  project/.settings/org.eclipse.wst.jsdt.ui.superType.container
  project/.settings/org.eclipse.wst.jsdt.ui.superType.name
Labels: 설정

#8 item,category,review,qa,qa_reqly VO 추가
  project/src/main/java/com/sist/vo/ItemCategoryVO.java
  project/src/main/java/com/sist/vo/ItemQAReplyVO.java
  project/src/main/java/com/sist/vo/ItemQAVO.java
  project/src/main/java/com/sist/vo/ItemReviewVO.java
  project/src/main/java/com/sist/vo/ItemVO.java
  project/src/main/webapp/index.jsp
Labels: 기능

#9 OrderVO,DeliveryVO,OrderItemVO 추가
  project/src/main/java/com/sist/vo/DeliveryVO.java
  project/src/main/java/com/sist/vo/OrderItemVO.java
  project/src/main/java/com/sist/vo/OrderVO.java
Labels: 기능

#13 MemberVO 추가
  project/src/main/java/com/sist/vo/MemberVO.java
Labels: 기능

#14 - footer 내용 수정 , location 이름 수정
  project/src/main/webapp/happy/fragments/footer.jsp
  project/src/main/webapp/index.jsp
Labels: 기능

#16 - 메인페이지 구성 추가
  project/src/main/java/com/sist/model/MainModel.java
  project/src/main/webapp/happy/main/main.jsp
Labels: 기능, 화면

#21 회원가입 및 로그인 페이지 추가
  project/src/main/java/com/sist/controller/DispatcherServlet.java
  project/src/main/java/com/sist/dao/ItemDAO.java
  project/src/main/java/com/sist/dao/MemberDAO.java
  project/src/main/java/com/sist/model/MemberModel.java
  project/src/main/webapp/WEB-INF/application.xml
  project/src/main/webapp/assets/images/main/logo/happy-logo-1.jpeg
  project/src/main/webapp/assets/images/main/logo/happy-logo-2.jpeg
  project/src/main/webapp/assets/images/main/logo/happy-logo-3.jpeg
  project/src/main/webapp/assets/project/member/css/signup.css
  project/src/main/webapp/assets/project/member/js/address.js
  project/src/main/webapp/assets/project/member/js/login.js
  project/src/main/webapp/assets/project/member/js/signup.js
  project/src/main/webapp/happy/fragments/footer.jsp
  project/src/main/webapp/happy/fragments/head.jsp
  project/src/main/webapp/happy/fragments/header.jsp
  project/src/main/webapp/happy/main/main.jsp
  project/src/main/webapp/happy/member/login.jsp
  project/src/main/webapp/happy/member/signup.jsp
Labels: 화면

#22 캠핑장 목록 및 상세 페이지 추가
  project/src/main/java/com/sist/dao/CampDAO.java
  project/src/main/java/com/sist/model/CampModel.java
  project/src/main/java/com/sist/util/Pagination.java
  project/src/main/webapp/WEB-INF/application.xml
  project/src/main/webapp/happy/camp/camp_detail.jsp
  project/src/main/webapp/happy/camp/camp_list.jsp
  project/src/main/webapp/happy/fragments/navigation.jsp
Labels: 기능, 화면
